
-- QUOTAS
ALTER USER "DEMO_RAFAL_TEST" QUOTA UNLIMITED ON "APEX_1650103465533182";

-- ROLES

-- SYSTEM PRIVILEGES
GRANT CREATE JOB TO "DEMO_RAFAL";
GRANT CREATE TRIGGER TO "DEMO_RAFAL";
GRANT CREATE MATERIALIZED VIEW TO "DEMO_RAFAL";
GRANT CREATE DIMENSION TO "DEMO_RAFAL";
GRANT CREATE OPERATOR TO "DEMO_RAFAL";
GRANT CREATE INDEXTYPE TO "DEMO_RAFAL";
GRANT CREATE VIEW TO "DEMO_RAFAL";
GRANT CREATE DOMAIN TO "DEMO_RAFAL";
GRANT CREATE SESSION TO "DEMO_RAFAL";
GRANT CREATE TABLE TO "DEMO_RAFAL";
GRANT CREATE PROPERTY GRAPH TO "DEMO_RAFAL";
GRANT CREATE TYPE TO "DEMO_RAFAL";
GRANT CREATE MLE TO "DEMO_RAFAL";
GRANT CREATE SYNONYM TO "DEMO_RAFAL";
GRANT CREATE SEQUENCE TO "DEMO_RAFAL";
GRANT EXECUTE DYNAMIC MLE TO "DEMO_RAFAL";
GRANT CREATE CLUSTER TO "DEMO_RAFAL";
GRANT CREATE PROCEDURE TO "DEMO_RAFAL";

