/* --------------------------
SQLcl popular settings 
-----------------------------
*/

/* How to check your actual settings? 
show define
show feedback
show serveroutput
or 
show all
*/

/* SET SQLPrompt 
By default each line starts with "SQL>"
Turn it off:
SET SQLPROMPT ""

Change to custom one:
SET SQLPROMPT "MySQLclCustomPrompt>>>"
*/
set sqlprompt "@|blue _USER|@@@|green _CONNECT_IDENTIFIER|@ > "

/* LINENUMBERS - controls whether to display line numbers in the SQL editor

SET LINENUMBERS ON [default]
SET LINENUMBERS OFF
*/


/* DEFINE  - enables & prompting
set define on [default]
set define off
Can be changed to e.g. # 
set define '#'
*/

/* FEEDBACK - controls whether to display the number of records returned/affected by a statement
set feedback on [default]
set feedback off
set feedback only - shows only the number of records returned/affected by a statement, without showing the actual data.
*/

/* SERVEROUTPUT - print or not output generated by DBMS_OUTPUT 
set serveroutput on
set serveroutput off [default]
*/
set serveroutput on

/* TERMOUT - controls whether to display the results of SQL commands when running a script
set termout on [default]
set termout off
TERMOUT only affects commands executed from a script file
*/

/* TIMING - controls whether to display the time taken to execute each SQL command or PL/SQL block
set timing on 
set timing off [default]
*/

/* SQLFORMAT  - change a way how your data is exported or displayed. 
                Resizes the columns to the width of the data to save space
set sqlformat

default is "default" - some old, ugly look

set sqlformat csv
set sqlformat ansiconsole
set sqlformat json
set sqlformat insert
set sqlformat loader
set sqlformat xml
set sqlformat html
set sqlformat delimited |
*/
set sqlformat ansiconsole

/* STATUSBAR - toolbar in your SQLcl session 
set statusbar on
set statusbar default linecol git project cwd  editmode txn 

linecol     - shows the current line and column number in the status bar
git         - shows the current git branch in the status bar
project     - shows the current project name in the status bar
cwd         - shows the current working directory in the status bar
txn         - shows the current transaction status
editmode   - shows the current editing mode (e.g., insert, overwrite)
timing     - shows the timing status (on/off) in the status bar
*/
set statusbar on 
set statusbar default username git project cwd txn timing

